### ISSUE TITLE
ADS1115 docs wrong constants

### ISSUE THREAD

**Issue by schumar** [OttoWinter/esphomedocs#11]
Hope it wasn't something I did wrong, but
https://esphomelib.com/api/sensor/ads1115.html
says
```
auto *sensor = ads1115->get_sensor("ADS1115 Voltage #1", ADS1115_MUX_P0_N1, ADS1115_PGA_6P144);
```
but I had to use `sensor::ADS1115_MULTIPLEXER_P0_N1` and `sensor::ADS1115_GAIN_6P144` instead (i.e. specify the namespace, and the const names are different).

**Comment by OttoWinter** [comment]
Ah thank you again! I recently rewrote the ADS1115 component to no longer depend on an external dependency. In the process I renamed a few of the constants and apparently forgot to update the API docs 😺
