### ISSUE TITLE
make the switch a light-switch

### ISSUE THREAD

**Issue by lasse9000** [OttoWinter/esphomedocs#118]
i have a sonoff 4ch pro i have ambede in esphome, and it works.

But, is it possible to make the switch as light-switch, so they work in google assistant or do i have to connect mqtt broker again to get it like the light-switch back again?

**Comment by OttoWinter** [comment]
https://esphomelib.com/esphomeyaml/components/light/binary.html
https://esphomelib.com/esphomeyaml/components/output/gpio.html

**Comment by lasse9000** [comment]
Thanks it works. but is there a way to make the automation so the button toggle the light-switch, so i can remove the switch section completly.

i have tryed
-light.switch: relay_1
-light.switch: gpio_d1
but an id: in the light 


binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff 4CH Button 1"
  on_press:
    - switch.toggle: relay_1

output:
  - platform: gpio
    pin: GPIO12
    id: gpio_d1

light:
  - platform: binary
    name: "Køkkenbord"
    output: gpio_d1
