### ISSUE TITLE
Build/test in Windows Docker - make: *** No rule to make target 'webserver'.  Stop.

### ISSUE THREAD

**Issue by DavidDeSloovere** [OttoWinter/esphomedocs#139]
On Windows, I can't test the docs via docker (using Linux containers).
Running the following command:

```docker run --rm -v ${PWD}/..:/data -p 8000:8000 -it ottowinter/esphomedocs```

Where ${PWD} is correct.

Image are downloaded, but on execution I get:

```make: *** No rule to make target 'webserver'.  Stop.```

(unfortunately, running the whole python/doxygen/sphinx pipeline isn't working on windows either)

**Comment by OttoWinter** [comment]
Where is your esphomedocs folder? Can you print your file structure?

**Comment by DavidDeSloovere** [comment]
Good call. Repo name is now ESPHome-Docs and I cloned it as such, not as esphomedocs (which was the previous name I presume)

`WORKDIR /data/esphomedocs`

![image](https://user-images.githubusercontent.com/352626/51848659-467b7d80-231e-11e9-9cd0-c44a23cdad23.png)

![image](https://user-images.githubusercontent.com/352626/51848703-5eeb9800-231e-11e9-8bc0-bdb4e067bf4e.png)

Renaming the ESPHome-Docs folder to esphomedocs allows me to start the docker image and browse the docs.
"Incorrect" name of ESPHome-Lib vs esphomelib has the same problem, but that's ok.

The data dir and volume mapping is probably required, but can't this be solved with the root parent of the docs repo instead of its parent via "$PWD/.." ?
Are you planning on updating paths in the docker file?

**Comment by OttoWinter** [comment]
Ok, the esphomelib folder is no longer necessary for building the docs. Plus you now get netlify deploy previews in PRs so no more need to local building anymore :)  (even managed to get build times to 1min 😎 )

**Comment by DavidDeSloovere** [comment]
just tried it on a new clone, ran the docker command (on windows) and it worked perfectly!
