### ISSUE TITLE
custom.rst missing information on required yaml settings ?

### ISSUE THREAD

**Issue by promd** [OttoWinter/esphomedocs#15]
While I was able to follow the instructions and go for a pio run, I can't use the custom sensor with esphomeyaml - is this by intent, or is the documentation incomplete ?

**Comment by OttoWinter** [comment]
What exactly is the error? I can't magically know why your setup isn't working... Anyway, yes there was something left out in the custom sensor docs but that will be resolved with the next docs deploy

**Comment by OttoWinter** [comment]
Should be fixed now :)
