### ISSUE TITLE
Problem with Sonoff TH10 & Si7021 sensor

### ISSUE THREAD

**Issue by gaimos** [OttoWinter/esphomedocs#152]
I test Sonoff TH10 with this firmware and have problem.
If set i2c scan to true i see in logs:
`[C][i2c:043]: I2C Bus:
[C][i2c:044]:   SDA Pin: GPIO4
[C][i2c:045]:   SCL Pin: GPIO5
[C][i2c:046]:   Frequency: 1000 Hz
[I][i2c:048]: Scanning i2c bus for active devices...
[I][i2c:064]: Found no i2c devices!`
If i set sda&scl manually - "Found no i2c devices!" again.
With dallas temperature sensor firmware work's perfectly.
Anyone know solution?

ps sensor tested and work with original firmware :)

**Comment by gaimos** [comment]
I found solution in pull request's. https://github.com/esphome/esphome-docs/pull/147
But now i see ` Unknown value 'SI7021', must be one of 'RHT03', 'DHT22', 'AM2302', 'AUTO_DETECT', 'DHT11'. Got 'SI7021'
  model: SI7021`.
When is version update expected?

**Comment by OttoWinter** [comment]
@gaimos You must use ESPHome dev version to have that feature.

Closing as issue has been fixed in dev.
