### ISSUE TITLE
ESPHome-docs docker image on unraid

### ISSUE THREAD

**Issue by erazor666** [OttoWinter/esphomedocs#174]
I'm trying to install the esphome-docs repo on my unraid docker server:

```
docker run -d --name='esphomedocs' --net='br0' --ip='10.0.0.57' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/appdata/esphomedocs/':'/data/esphomedocs':'rw' 'esphome/esphome-docs' 
69aebf895ccb228653bbf024d5d1c1afde25fc7fc409a3f4a578b2c996315b16
```

but when i try to start the container it fails and outputs this in its log
```
make: *** No rule to make target 'webserver'. Stop.
make: *** No rule to make target 'webserver'. Stop.
```

Is there anything wrong with my docker command there?

(I apologize if this is not supposed to be posted here, please move to correct place if this is not the proper place for posting issues with esphome-docs)

**Comment by nnmalex** [comment]
@erazor666 The Docker image doesn't contain the documents, only the doxygen server. You have to clone this git repo with the docks to get started.

@OttoWinter there's an error in the docker image though (supposedly) - it points to the "esphomedocs" directory while the repo clones to "esphome-docs".

Also Makefile refers to the BUILDDIR that is not defined.
