### ISSUE TITLE
Can you add validate button to EDIT window?

### ISSUE THREAD

**Issue by poldim** [OttoWinter/esphomedocs#188]
Just wondering if there is a way to add this functionality to initiate the validation process without leaving the edit page.  It would be nice, since as a beginner with ESPHome, I find myself constantly editing and validating the yaml to try to solve issues.

I know there may be some challenges with having the validation process with the edit window open, but maybe the validating would run on-top-on the edit window.  This way if the validation is unsuccessful, you get to see the results of why, and then you would click the normal close button to close the validation screen and be prompted with the edit screen.  If the validation is successful, maybe you could present an upload button.

<img width="1069" alt="esphome dashboard 2019-03-02 14-19-00" src="https://user-images.githubusercontent.com/16869713/53688275-85726980-3cf6-11e9-927e-2a1e85715ac5.png">

**Comment by OttoWinter** [comment]
See https://github.com/esphome/esphome-docs/issues/162

And that would be nice, however I do not want to have a second modal pop up in front of the edit one. The whole dashboard needs to be redesigned a little to do this. Unfortunately I'm no web developer and do not have the time for that. Maybe someone else can tackle this
