### ISSUE TITLE
HDC1080 image missing

### ISSUE THREAD

**Issue by janpieper** [OttoWinter/esphomedocs#19]
The HDC1080 image is missing in the _Sensor Components_ section.

* https://esphomelib.com/_images/hdc1080.jpg <-- 404 Not Found

Tried to create a PR for this to get it back working, but I don't get why it is missing, because here it is:

* https://github.com/OttoWinter/esphomedocs/blob/current/esphomeyaml/images/hdc1080.jpg

The image for the DHT12 sensor is available and uses the same locations:

* https://esphomelib.com/_images/dht12.jpg
* https://github.com/OttoWinter/esphomedocs/blob/current/esphomeyaml/images/dht12.jpg

Seems like a server issue :man_shrugging:

**Comment by OttoWinter** [comment]
Uhm, the PR you linked did fix the issue, I was just too lazy to re-build the webpage as that is quite a pain in the arse. Fortunately, with the next release most of the docs deploy pipeline has been automated so that should hopefully not be an issue anymore.
