### ISSUE TITLE
Add Skywriter 3D Gesture Sensing Breakout to ESPHome

### ISSUE THREAD

**Issue by bachoo786** [OttoWinter/esphomedocs#197]
Hi 

I was wondering if you could please add the Skywriter: 3D Gesture Sensing Breakout to ESPHOME. The link is here: https://shop.pimoroni.com/products/skywriter?variant=1047423445&gclid=EAIaIQobChMIu5KPyLX84AIVls13Ch1rVwRYEAQYByABEgKvkPD_BwE#description

It would be great to control other devices maybe via MQTT using the Skywriter 3D as it can penetrate through wood and longer distances than other gesture sensors.

Thanks.

**Comment by OttoWinter** [comment]
https://github.com/esphome/esphome-docs/issues/162
