### ISSUE TITLE
BME280 wrong values

### ISSUE THREAD

**Issue by Palkin81** [OttoWinter/esphomedocs#21]
The BME280 sensor produces absolutely incorrect values. With another firmware ESP8266 all okay. What could it be?
![screen](https://user-images.githubusercontent.com/11413396/44927278-a3b5d780-ad5c-11e8-9a7d-88e3fc188248.png)

Esp8266 nodemcu v2 + bme280 sensor

**Comment by OttoWinter** [comment]
Should be fixed with the next release which will probably be released in the next few days.
