### ISSUE TITLE
Intel NUC Hassio errors

### ISSUE THREAD

**Issue by LuisCanossa** [OttoWinter/esphomedocs#54]
Hello.
I have the hassio installed on Intel NUC in docker (Ubuntu 18.04.1 LTS)
I install the addon but when compile gives the following error:

[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22ArduinoOTA%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb701f5ac>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=1)

**Comment by OttoWinter** [comment]
This is an issue with HassIO (their DNS settings were wrong). Please try to upgrade to the latest HassIO system.
