### ISSUE TITLE
Cookbook: mqtt-bmp180-oled.yaml

### ISSUE THREAD

**Issue by rradar** [OttoWinter/esphomedocs#87]
I was inspired by mqtt-bme280-homie (https://github.com/mhaack/mqtt-bme280-homie/) and wanted to extend it to also work without active wifi/mqtt connection (https://github.com/mhaack/mqtt-bme280-homie/issues/6). What would be the best job for it? For sure esphomeyaml! :sparkles: :sparkler: :fireworks: 

**Part list:**
- esp m3 (for any other esp/board just change platform/board in your yaml!)
![image](https://user-images.githubusercontent.com/34582688/49089786-95dcf900-f25c-11e8-9d33-aed1278345f2.png)
- bmp180/bmp085 (or for bme280 change the sensor platform)
![image](https://user-images.githubusercontent.com/34582688/49089914-e9e7dd80-f25c-11e8-9270-9a93539148ba.png)
- oled display
![image](https://user-images.githubusercontent.com/34582688/49090404-ea34a880-f25d-11e8-9bb2-764392564bd2.png)
- some wires (for example dupont cables) to hook things up

The total hardware costs are around $5 when ordered directly from the country of origin.

For the font I used five by five licensed under CC BY 4.0 from dafont: https://www.dafont.com/de/fivebyfive.font
```
esphomeyaml:
  name: mqtt-bmp180-oled
  platform: ESP8266
  board: esp8285

wifi:
  ssid: 'xxx'
  password: 'xxx'

mqtt:
  broker: 'xxx'
  username: 'xxx'
  password: 'xxx'

# Enable logging
logger:

ota:
  password: 'xxx'

i2c:
  sda: 0
  scl: 2
  scan: False

binary_sensor:
  - platform: status
    name: "mqtt-bmp180-oled Status"
    id: status

sensor:
  - platform: wifi_signal
    name: "mqtt-bmp180-oled WiFi Signal"
    update_interval: 60s
    id: signal

  - platform: bmp085
    temperature:
      name: "mqtt-bmp180-oled Temperature"
      id: temperature
    pressure:
      name: "mqtt-bmp180-oled Pressure"
      id: pressure
    update_interval: 60s

switch:
  - platform: restart
    name: "mqtt-bmp180-oled Restart"

font:
  - file: "five.ttf"
    id: five8
    size: 8

time:
  - platform: sntp
    id: time
    servers:
      - 0.pool.ntp.org

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda:  |-
      it.printf(0, 10, id(five8), "Temp: %.1f Celsius", id(temperature).value);
      it.printf(0, 20, id(five8), "Pressure: %.1f hPa", id(pressure).value);
      it.strftime(0, 35, id(five8), "Time: %H:%M", id(time).now());
      it.strftime(0, 45, id(five8), "Date: %d.%m.%Y", id(time).now());
      it.printf(0, 60, id(five8), "Wifi: %s", id(status).value ? "Online" : "Offline");
      it.printf(80, 60, id(five8), "%.1f", id(signal).value);
```

And the result looks like this:

![image](https://user-images.githubusercontent.com/34582688/49089179-41854980-f25b-11e8-8424-dd792896d8ee.png)

**Comment by rradar** [comment]
Little off topic: the original homie sketch by @mhaack has 4 pages (Temperature, Humidity, etc.) witha very nice layout and a very nice sliding animation/effect while changing the single pages.

Looks a little bit like this and is probably based on homie-display (https://github.com/luebbe/homie-display) from @luebbe

![image](https://user-images.githubusercontent.com/34582688/49090899-fa00bc80-f25e-11e8-8062-47e22581a98f.png)
![image](https://user-images.githubusercontent.com/34582688/49090973-2ae0f180-f25f-11e8-8198-070980e0f569.png)

Something like this (more than one page and animations) is not ***yet*** possible with esphomeyaml - right :question:  :grin:

**Comment by OttoWinter** [comment]
Awesome setup! Thanks for sharing!

By cookbook entry I meant creating an entry here: https://esphomelib.com/esphomeyaml/index.html#cookbook 😅

I will try to convert this guide to [the docs format](https://esphomelib.com/esphomeyaml/guides/contributing.html#contributing-to-esphomedocs) soon, so that other users can profit from this :)

@rradar As for the last post: Yes, more than one page is possible:

``` yaml
display:
- platform: some_platform
  lambda: |-
    static int i = 1;
    if (i == 1) {
      // draw first page
      i = 1;
    } else if (i == 2) {
      // draw second page
      i = 3;
    } else if (i == 3) {
      // draw last page
      i = 1;
    }
```

but animations: no, at least not easily. As you have direct access to the display (you can draw each pixel individually) it is of course technically possible, although it would not be fun to implement.

Animations would need a major rethink of the display engine. This "draw the entire display from scratch every time" approach is great for quick development, but makes animations difficult. Animations would require a framework where you first add a bunch of *widgets* at setup time and modify them each frame.

**Comment by rradar** [comment]
@OttoWinter I'm trying right now to show more than one page (my idea was to switch the pages after n seconds). I'm not sure how to implement this. With your sketch just page one get's shown. What would be the trigger to change the page here?

Herzliches Dankeschön!

**Comment by rradar** [comment]
Sorry again for asking but how are the pages triggered with this sketch?

```
display:
- platform: some_platform
  lambda: |-
    static int i = 1;
    if (i == 1) {
      // draw first page
      i = 1;
    } else if (i == 2) {
      // draw second page
      i = 3;
    } else if (i == 3) {
      // draw last page
      i = 1;
    }
```

It always stays on page 1 for me? :confused:

**Comment by flozsc** [comment]
> It always stays on page 1 for me? 😕

I think you'll need to set i to 2 after drawing the first page - probably a typo.

```
display:
- platform: some_platform
  lambda: |-
    static int i = 1;
    if (i == 1) {
      // draw first page
      i = 2;                     // <-- *here*
    } else if (i == 2) {
      // draw second page
      i = 3;
    } else if (i == 3) {
      // draw last page
      i = 1;
    }
```

**Comment by dobrynski** [comment]
Couldn't the `i` be the the output from another sensor/input? some sort of toggle.. or timer?

**Comment by rradar** [comment]
@mihalski 
I thought a timer (for example 15 seconds) would be sufficient for the first working sketch. Any ideas how to implement this?

**Comment by Mynasru** [comment]
Isn't `i` updated every time the display updates (`update_interval`)?

**Comment by hajdbo** [comment]
where can we find the five.ttf font?

**Comment by minsuke** [comment]
hello 

can I make a image change process, conditional weather condition. ? 

ex) if 1 then cloudy image, if 2 then sunny image. 

I don't know how to make it.

**Comment by OttoWinter** [comment]
@minsuke You'd need to use some C++ if conditions to do that (I think some of the cookbooks on https://esphome.io may have some examples for that).

Anyway, I'm closing this issue because the cookbook is now on esphome.io - not in the GitHub issue section.
