### ISSUE TITLE
[Feature Request] Sea level correction for air pressure sensor

### ISSUE THREAD

**Issue by exxamalte** [OttoWinter/esphomedocs#89]
It would be nice to be able to configure the altitude in metres for air pressure sensors like the BME280 and use that to calculate the air pressure at sea level.

I just found this code snippet that would help:
```
double bmp_atSealevel(double pressure)
{
  return pressure / pow(1.0 - ((float)altitude / 44330.0), 5.255);
}
```

**Comment by Mynasru** [comment]
Maybe also useful is to calculate the sensors altitude based on the current sea level pressure:
[Adafruit BMP280](https://github.com/adafruit/Adafruit_BMP280_Library/blob/master/Adafruit_BMP280.cpp#L340)
More formulas and explanation: [PDF](https://www.sandhurstweather.org.uk/barometric.pdf)

I'll try to make a cookbook entry soon.
