### ISSUE TITLE
[Question] Draw '%' on LCD and utilize more than one page

### ISSUE THREAD

**Issue by rradar** [OttoWinter/esphomedocs#96]
Hello,

I'm playing with a i2c LCD Display ([PCF8574](https://esphomelib.com/esphomeyaml/components/display/lcd_pcf8574.html)) and having a great time! :sparkle: 

I'm just struggling get a '%' behind my humidity printed. I read the [docs](https://esphomelib.com/esphomeyaml/components/display/index.html#display-printf) but didn't got smarter.

Another question is how can I utilize more than one page or let content scrolling?

Thank's for the help already!

**Comment by rradar** [comment]
Ugly fix:

`'/.`

uses three columns :cry:

**Comment by OttoWinter** [comment]
Did you see https://esphome.io/components/display/index.html?highlight=literal%20sign ?

Also, if your display character set doesn't include the % character there's no way to add it manually. (though this one seems to support it: https://mil.ufl.edu/3744/docs/lcdmanual/charset.gif)

Closing as limitation of the display
